#Moja strona

Hejka! 
theme: jekyll-theme-minimal
title: Moja strona 
Jestem studentką Akademii Górniczo-Hutniczej na AGH. Moim największym zainteresowaniem ( do paźdiernika ) była matematyka, obecnie jest to sport. Wraz z przyjaciółmi 
pracujemy nad stworzeniem strony Internetowej, na której będzie można znaleźć wszelkie informacje dotyczące wielkich wydarzeń w Polsce. 
Coś o mnie
- nie od zawsze chciałam studiować Informatykę - jak byłam mała chciałam być psychologiem, później całe gimnazjum byłam przekonana, że będę studiować kierunek 
humanistyczny ale nigdy nie szło mi dobrze z polskiego, ani historii - właściwie nienawidziłam tych przedmiotów. W liceum chciałam studiować medycynę aczkolwiek
tam też narodziła się moja miłość do matematyki i Informatyki i w ten dziwny sposób jestem tutaj :) 



